// <auto-generated />
using System;
using AppDotnet01;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AppDotnet01.Migrations
{
    [DbContext(typeof(Contexto))]
    partial class ContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AppDotnet01.ConsumoMaterial", b =>
                {
                    b.Property<int>("idConsumo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idConsumo"), 1L, 1);

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("IDMaterial")
                        .HasColumnType("int");

                    b.Property<int>("IDTarea")
                        .HasColumnType("int");

                    b.HasKey("idConsumo");

                    b.HasIndex("IDMaterial");

                    b.HasIndex("IDTarea");

                    b.ToTable("ConsumoMateriales");
                });

            modelBuilder.Entity("AppDotnet01.Material", b =>
                {
                    b.Property<int>("codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("codigo"), 1L, 1);

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("precio")
                        .HasColumnType("int");

                    b.HasKey("codigo");

                    b.ToTable("Materiales");
                });

            modelBuilder.Entity("AppDotnet01.Proyecto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Proyectos");
                });

            modelBuilder.Entity("AppDotnet01.Tarea", b =>
                {
                    b.Property<int>("IDTarea")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDTarea"), 1L, 1);

                    b.Property<int>("IDProyecto")
                        .HasColumnType("int");

                    b.Property<string>("avance")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDTarea");

                    b.HasIndex("IDProyecto");

                    b.ToTable("Tareas");
                });

            modelBuilder.Entity("AppDotnet01.ConsumoMaterial", b =>
                {
                    b.HasOne("AppDotnet01.Material", "material")
                        .WithMany()
                        .HasForeignKey("IDMaterial")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppDotnet01.Tarea", "tarea")
                        .WithMany()
                        .HasForeignKey("IDTarea")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("material");

                    b.Navigation("tarea");
                });

            modelBuilder.Entity("AppDotnet01.Tarea", b =>
                {
                    b.HasOne("AppDotnet01.Proyecto", "proyecto")
                        .WithMany()
                        .HasForeignKey("IDProyecto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("proyecto");
                });
#pragma warning restore 612, 618
        }
    }
}
